env:
  CIRRUS_CLONE_DEPTH: 1
  VT_TYPE: qemu

fedora_34_task:
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-fedora-34
    kvm: true
  env:
    matrix:
      # Get deps from setup.py (therefor pip version of avocado)
      - AVOCADO_SRC:
      # Latest LTS release is 82.x
      - AVOCADO_SRC: avocado-framework<83.0
      # Latest Avocado from git
      - AVOCADO_SRC: git+https://github.com/avocado-framework/avocado#egg=avocado_framework
    matrix:
      - SETUP: setup.py develop --user
      - SETUP: -m pip install .
      - SETUP: -m pip install PYPI_UPLOAD/*.whl
    matrix:
      - VT_TYPE: qemu
      - VT_TYPE: libvirt
  build_script:
    - (echo $SETUP | grep -v PYPI_UPLOAD) || make pypi
  setup_script: &setup_scr
    - python3 --version
    - test -z $AVOCADO_SRC || python3 -m pip install $AVOCADO_SRC
    - python3 $SETUP
  bootstrap_script: &bootstrap_scr
    - python3 -m avocado vt-bootstrap --vt-type=$VT_TYPE --vt-skip-verify-download-assets --yes-to-all
  list_script: &list_scr
    - python3 -m avocado list --vt-save-config=/tmp/config --vt-type=$VT_TYPE -- boot | tee /tmp/list
    - test $VT_TYPE == "qemu" || test $(wc -l < /tmp/list) -gt 50
    - test $VT_TYPE == "libvirt" || test $(wc -l < /tmp/list) -eq 1
    - python3 -m avocado list --vt-config=/tmp/config --vt-type=$VT_TYPE -- boot | tee /tmp/list_from_config
    - diff /tmp/list /tmp/list_from_config
    - python3 -m avocado vt-list-guests --vt-type=$VT_TYPE
    - python3 -m avocado vt-list-archs --vt-type=$VT_TYPE
  dry_run_script: &dry_run_scr
    - python3 -m avocado --show all run --vt-type=$VT_TYPE --dry-run -- io-github-autotest-qemu.boot
  run_boot_script: &run_boot_scr
    - test $VT_TYPE == "libvirt" || PATH=$HOME/.local/bin:$PATH python3 -m avocado --show all run --vt-type=$VT_TYPE --vt-extra-params nettype=user -- io-github-autotest-qemu.boot

centos_8_1_task:
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-centos-8.1
  env:
    matrix:
      - AVOCADO_SRC:
      - AVOCADO_SRC: avocado-framework<70.0
      - AVOCADO_SRC: git+https://github.com/avocado-framework/avocado#egg=avocado_framework
    matrix:
      - SETUP: setup.py develop --user
      - SETUP: -m pip install .
  setup_script:
    *setup_scr
  bootstrap_script:
    *bootstrap_scr
  list_script:
    *list_scr
  dry_run_script:
    *dry_run_scr
