name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            .tox
          key: ${{ matrix.os }}-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: tox
        run: |
          python3.8 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install tox
          .venv/bin/tox -q -p all
